### ISSUE TITLE
Infografia de los sistemas numericos

### ISSUE THREAD

**Issue by W1ll1am21** [SistemasTecTlaxiaco/infografia-W1ll1am21#1]
[INFOGRAFIA MATEMATICAS DISCRETAS.pdf](https://github.com/user-attachments/files/16741715/INFOGRAFIA.MATEMATICAS.DISCRETAS.pdf)

**Comment by QUET012** [comment]
Redacción y ortografía:14/14
Exposición de ideas centrales:15/16
Organización de ideas centrales:13/14
uso de imágenes y colores:14/14
presentación visual:14/14
referencias:14/14
presentacion:14/14
calificación
 final:19.6

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
